-- СТУДЕНТ ТУРАЛЫ АҚПАРАТ
INSERT INTO student (first_name, last_name, gender) VALUES ('Cyndie', 'De''Ath', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Daloris', 'Sharpin', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Shandie', 'Kingzeth', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Trev', 'Spere', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Nero', 'Laying', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Rina', 'Gilardengo', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Aleta', 'Greves', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Johnathan', 'Nulty', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Rudolf', 'Liquorish', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Osmond', 'Clinning', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Anabelle', 'Jiracek', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Leshia', 'Kilmurry', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Janeva', 'Farnsworth', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Jeremias', 'Sawtell', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Travus', 'Boman', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Hashim', 'Huniwall', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Worth', 'Rennebeck', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Kinsley', 'Deetlefs', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Harbert', 'Stidson', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Domingo', 'Ferres', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Muire', 'Van Der Walt', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Kris', 'Lanston', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Ingamar', 'Callery', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Drusilla', 'Hopfner', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Elvera', 'Nell', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Esma', 'Pleuman', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Sayres', 'Ramel', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Culley', 'Debenham', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Oliy', 'Hoolaghan', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Conni', 'Sawell', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Umberto', 'Halpen', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Rania', 'Parramore', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Annabella', 'Hattam', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Pattie', 'Thomelin', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Zeb', 'Wordsley', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Judas', 'Pearch', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Giacomo', 'Rae', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Luella', 'Rheam', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Derril', 'Touret', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Bondy', 'Kingsmill', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Kin', 'Conaboy', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Devina', 'Puttan', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Christie', 'Sear', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Leon', 'Give', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Bonny', 'Marzelli', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Emlen', 'Gonthard', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Marlowe', 'Clappison', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Boony', 'Dacks', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Lawton', 'Bette', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Sarah', 'Brittle', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Matthiew', 'Lammerding', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Ole', 'Attock', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Egbert', 'Beine', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Gabbi', 'Wyldes', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Fianna', 'Mawson', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Jaine', 'Pagett', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Agace', 'Waggatt', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Rube', 'Pic', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Anatole', 'Dudhill', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Nye', 'Simoncello', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Baryram', 'Pawellek', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Emmanuel', 'Sewart', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Mallory', 'Padfield', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Carlyle', 'Tadlow', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Cammi', 'Henric', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Honey', 'Trevear', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Nester', 'Troppmann', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Upton', 'Posner', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Maddy', 'Danielsson', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Teddie', 'Genge', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Maryrose', 'Lomis', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Kelcy', 'Gregor', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Shadow', 'De Morena', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Forrest', 'Bysshe', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Lauryn', 'Quirke', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Magnum', 'Carpmile', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Norbie', 'Dyball', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Christophorus', 'Blackall', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Des', 'Attree', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Devonne', 'Moquin', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Kaye', 'Kapiloff', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Parry', 'Cornhill', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Cesare', 'Blundan', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Gaynor', 'St Leger', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Karyl', 'Deeley', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Arnoldo', 'Tasseler', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Francesca', 'Runsey', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Adolphe', 'Ivison', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Beckie', 'Beretta', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Hartley', 'Le Jean', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Berke', 'McKissack', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Averil', 'Enever', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Jessie', 'Upfold', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Joscelin', 'Espinazo', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Justin', 'Dyter', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Lawton', 'Leverson', 'Male');
INSERT INTO student (first_name, last_name, gender) VALUES ('Fannie', 'Olivi', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Nan', 'Minchell', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Roanne', 'Luigi', 'Female');
INSERT INTO student (first_name, last_name, gender) VALUES ('Ermanno', 'Sexon', 'Male');

-- student info 
insert into student_info (student_id, class, address) values (1, '11A', '2 Coolidge Park');
insert into student_info (student_id, class, address) values (2, '11A', '5300 Manitowish Pass');
insert into student_info (student_id, class, address) values (3, '11A', '036 Dorton Avenue');
insert into student_info (student_id, class, address) values (4, '11A', '118 Dennis Avenue');
insert into student_info (student_id, class, address) values (5, '11A', '1 Leroy Crossing');
insert into student_info (student_id, class, address) values (6, '11B', '12914 South Way');
insert into student_info (student_id, class, address) values (7, '11B', '366 Oakridge Hill');
insert into student_info (student_id, class, address) values (8, '11B', '3173 Atwood Park');
insert into student_info (student_id, class, address) values (9, '11B', '25 Mallory Trail');
insert into student_info (student_id, class, address) values (10, '11B', '12156 Columbus Place');
insert into student_info (student_id, class, address) values (11, '11B', '177 Cottonwood Terrace');
insert into student_info (student_id, class, address) values (12, '11B', '96 Springs Junction');
insert into student_info (student_id, class, address) values (13, '11B', '42 Petterle Hill');
insert into student_info (student_id, class, address) values (14, '11B', '3 Florence Pass');
insert into student_info (student_id, class, address) values (15, '11B', '72 Burrows Court');
insert into student_info (student_id, class, address) values (16, '11B', '757 Upham Pass');
insert into student_info (student_id, class, address) values (17, '11B', '2320 Knutson Crossing');
insert into student_info (student_id, class, address) values (18, '11B', '92500 Chive Drive');
insert into student_info (student_id, class, address) values (19, '11B', '8 Drewry Place');
insert into student_info (student_id, class, address) values (20, '11B', '61878 Northridge Street');
insert into student_info (student_id, class, address) values (21, '11B', '14 Tony Junction');
insert into student_info (student_id, class, address) values (22, '11B', '70209 Swallow Drive');
insert into student_info (student_id, class, address) values (23, '11B', '9275 Springs Hill');
insert into student_info (student_id, class, address) values (24, '11B', '3 La Follette Point');
insert into student_info (student_id, class, address) values (25, '11B', '9 Texas Drive');
insert into student_info (student_id, class, address) values (26, '11B', '04 Darwin Court');
insert into student_info (student_id, class, address) values (27, '11B', '94100 Hooker Way');
insert into student_info (student_id, class, address) values (28, '11B', '736 Schmedeman Parkway');
insert into student_info (student_id, class, address) values (29, '11C', '2369 Blackbird Crossing');
insert into student_info (student_id, class, address) values (30, '11A', '296 Derek Lane');
insert into student_info (student_id, class, address) values (31, '11B', '229 Burning Wood Park');
insert into student_info (student_id, class, address) values (32, '11B', '8 Prairie Rose Pass');
insert into student_info (student_id, class, address) values (33, '11B', '90 Maple Wood Drive');
insert into student_info (student_id, class, address) values (34, '10A', '6 Harper Center');
insert into student_info (student_id, class, address) values (35, '10A', '23911 Sutteridge Park');
insert into student_info (student_id, class, address) values (36, '10A', '7925 Lerdahl Junction');
insert into student_info (student_id, class, address) values (37, '10A', '21 Fallview Park');
insert into student_info (student_id, class, address) values (38, '10A', '3 Arkansas Park');
insert into student_info (student_id, class, address) values (39, '11B', '4095 Macpherson Court');
insert into student_info (student_id, class, address) values (40, '11C', '347 Park Meadow Hill');
insert into student_info (student_id, class, address) values (41, '11C', '14316 Rieder Court');
insert into student_info (student_id, class, address) values (42, '10A', '5979 Mesta Trail');
insert into student_info (student_id, class, address) values (43, '11A', '103 Granby Terrace');
insert into student_info (student_id, class, address) values (44, '11A', '1 Dottie Court');
insert into student_info (student_id, class, address) values (45, '11A', '77 Jenifer Place');
insert into student_info (student_id, class, address) values (46, '11B', '870 Dixon Alley');
insert into student_info (student_id, class, address) values (47, '10C', '02 Lerdahl Point');
insert into student_info (student_id, class, address) values (48, '10B', '6 Cody Way');
insert into student_info (student_id, class, address) values (49, '10B', '3 Johnson Plaza');
insert into student_info (student_id, class, address) values (50, '10B', '97702 Mandrake Road');
insert into student_info (student_id, class, address) values (51, '10B', '63283 Darwin Park');
insert into student_info (student_id, class, address) values (52, '10B', '968 Warrior Crossing');
insert into student_info (student_id, class, address) values (53, '10B', '4 Lyons Place');
insert into student_info (student_id, class, address) values (54, '10B', '95265 Jay Street');
insert into student_info (student_id, class, address) values (55, '10C', '82601 Pearson Street');
insert into student_info (student_id, class, address) values (56, '10C', '22096 Gerald Alley');
insert into student_info (student_id, class, address) values (57, '11A', '31 Schiller Street');
insert into student_info (student_id, class, address) values (58, '11C', '43823 Prairieview Place');
insert into student_info (student_id, class, address) values (59, '11C', '938 2nd Place');
insert into student_info (student_id, class, address) values (60, '11C', '36 Heffernan Drive');
insert into student_info (student_id, class, address) values (61, '11C', '97 Londonderry Point');
insert into student_info (student_id, class, address) values (62, '11C', '5618 Nova Point');
insert into student_info (student_id, class, address) values (63, '11C', '02 Artisan Crossing');
insert into student_info (student_id, class, address) values (64, '10C', '4456 Corben Terrace');
insert into student_info (student_id, class, address) values (65, '10B', '2 Forest Center');
insert into student_info (student_id, class, address) values (66, '10A', '8559 Michigan Point');
insert into student_info (student_id, class, address) values (67, '10A', '60 Warrior Alley');
insert into student_info (student_id, class, address) values (68, '10A', '74 Schmedeman Street');
insert into student_info (student_id, class, address) values (69, '10A', '0031 Hoard Hill');
insert into student_info (student_id, class, address) values (70, '11B', '19127 Helena Place');
insert into student_info (student_id, class, address) values (71, '11C', '2 Evergreen Pass');
insert into student_info (student_id, class, address) values (72, '11A', '9 Fordem Hill');
insert into student_info (student_id, class, address) values (73, '11A', '81 Sheridan Plaza');
insert into student_info (student_id, class, address) values (74, '11A', '33 Northfield Court');
insert into student_info (student_id, class, address) values (75, '10B', '44797 Lakewood Gardens Park');
insert into student_info (student_id, class, address) values (76, '10B', '2540 Forster Junction');
insert into student_info (student_id, class, address) values (77, '10C', '11462 Warner Trail');
insert into student_info (student_id, class, address) values (78, '10C', '551 Spaight Crossing');
insert into student_info (student_id, class, address) values (79, '11B', '0210 Springs Pass');
insert into student_info (student_id, class, address) values (80, '11A', '04 Mcbride Crossing');
insert into student_info (student_id, class, address) values (81, '11C', '371 Colorado Street');
insert into student_info (student_id, class, address) values (82, '11B', '4074 Eagan Point');
insert into student_info (student_id, class, address) values (83, '11A', '763 Sunbrook Trail');
insert into student_info (student_id, class, address) values (84, '11A', '0228 Raven Avenue');
insert into student_info (student_id, class, address) values (85, '11A', '883 Red Cloud Crossing');
insert into student_info (student_id, class, address) values (86, '11A', '66457 Jay Avenue');
insert into student_info (student_id, class, address) values (87, '10A', '87 Superior Court');
insert into student_info (student_id, class, address) values (88, '10C', '4 Anthes Way');
insert into student_info (student_id, class, address) values (89, '10C', '91 Claremont Junction');
insert into student_info (student_id, class, address) values (90, '10C', '233 Harbort Pass');
insert into student_info (student_id, class, address) values (91, '11C', '74 Little Fleur Place');
insert into student_info (student_id, class, address) values (92, '11A', '08 Rutledge Hill');
insert into student_info (student_id, class, address) values (93, '11B', '0772 Briar Crest Lane');
insert into student_info (student_id, class, address) values (94, '10A', '3687 8th Place');
insert into student_info (student_id, class, address) values (95, '10A', '7253 Kingsford Crossing');
insert into student_info (student_id, class, address) values (96, '10A', '6 Waywood Avenue');
insert into student_info (student_id, class, address) values (97, '10A', '2759 Barby Park');
insert into student_info (student_id, class, address) values (98, '11C', '28 Alpine Plaza');
insert into student_info (student_id, class, address) values (99, '11C', '781 4th Terrace');
insert into student_info (student_id, class, address) values (100, '11B', '14725 Lerdahl Center');

-- subjects
INSERT INTO subject (name) VALUES ('MATH');
INSERT INTO subject (name) VALUES ('HISTORY');
INSERT INTO subject (name) VALUES ('BIOLOGY');
INSERT INTO subject (name) VALUES ('GEOGRAPHY');
INSERT INTO subject (name) VALUES ('ENGLISH');
INSERT INTO subject (name) VALUES ('INFORMATICS');

-- ss
insert into student_subject (student_id, subject_id) values (67, 4);
insert into student_subject (student_id, subject_id) values (30, 5);
insert into student_subject (student_id, subject_id) values (22, 5);
insert into student_subject (student_id, subject_id) values (52, 3);
insert into student_subject (student_id, subject_id) values (14, 5);
insert into student_subject (student_id, subject_id) values (19, 4);
insert into student_subject (student_id, subject_id) values (43, 4);
insert into student_subject (student_id, subject_id) values (78, 4);
insert into student_subject (student_id, subject_id) values (99, 5);
insert into student_subject (student_id, subject_id) values (38, 4);
insert into student_subject (student_id, subject_id) values (82, 1);
insert into student_subject (student_id, subject_id) values (16, 2);
insert into student_subject (student_id, subject_id) values (65, 6);
insert into student_subject (student_id, subject_id) values (2, 4);
insert into student_subject (student_id, subject_id) values (35, 4);
insert into student_subject (student_id, subject_id) values (74, 1);
insert into student_subject (student_id, subject_id) values (25, 2);
insert into student_subject (student_id, subject_id) values (42, 5);
insert into student_subject (student_id, subject_id) values (12, 5);
insert into student_subject (student_id, subject_id) values (90, 5);
insert into student_subject (student_id, subject_id) values (61, 1);
insert into student_subject (student_id, subject_id) values (58, 6);
insert into student_subject (student_id, subject_id) values (76, 4);
insert into student_subject (student_id, subject_id) values (79, 4);
insert into student_subject (student_id, subject_id) values (22, 4);
insert into student_subject (student_id, subject_id) values (30, 4);
insert into student_subject (student_id, subject_id) values (83, 5);
insert into student_subject (student_id, subject_id) values (21, 2);
insert into student_subject (student_id, subject_id) values (14, 2);
insert into student_subject (student_id, subject_id) values (56, 6);
insert into student_subject (student_id, subject_id) values (50, 3);
insert into student_subject (student_id, subject_id) values (16, 5);
insert into student_subject (student_id, subject_id) values (23, 5);
insert into student_subject (student_id, subject_id) values (88, 2);
insert into student_subject (student_id, subject_id) values (8, 6);
insert into student_subject (student_id, subject_id) values (67, 6);
insert into student_subject (student_id, subject_id) values (81, 3);
insert into student_subject (student_id, subject_id) values (69, 2);
insert into student_subject (student_id, subject_id) values (53, 6);
insert into student_subject (student_id, subject_id) values (43, 3);
insert into student_subject (student_id, subject_id) values (21, 4);
insert into student_subject (student_id, subject_id) values (56, 5);
insert into student_subject (student_id, subject_id) values (97, 1);
insert into student_subject (student_id, subject_id) values (84, 5);
insert into student_subject (student_id, subject_id) values (84, 1);
insert into student_subject (student_id, subject_id) values (14, 6);
insert into student_subject (student_id, subject_id) values (62, 3);
insert into student_subject (student_id, subject_id) values (54, 1);
insert into student_subject (student_id, subject_id) values (33, 2);
insert into student_subject (student_id, subject_id) values (68, 6);
insert into student_subject (student_id, subject_id) values (43, 5);
insert into student_subject (student_id, subject_id) values (59, 1);
insert into student_subject (student_id, subject_id) values (25, 1);
insert into student_subject (student_id, subject_id) values (87, 5);
insert into student_subject (student_id, subject_id) values (85, 5);
insert into student_subject (student_id, subject_id) values (39, 1);
insert into student_subject (student_id, subject_id) values (82, 5);
insert into student_subject (student_id, subject_id) values (50, 1);
insert into student_subject (student_id, subject_id) values (9, 4);
insert into student_subject (student_id, subject_id) values (34, 2);
insert into student_subject (student_id, subject_id) values (29, 5);
insert into student_subject (student_id, subject_id) values (28, 4);
insert into student_subject (student_id, subject_id) values (15, 2);
insert into student_subject (student_id, subject_id) values (62, 5);
insert into student_subject (student_id, subject_id) values (56, 1);
insert into student_subject (student_id, subject_id) values (80, 1);
insert into student_subject (student_id, subject_id) values (57, 1);
insert into student_subject (student_id, subject_id) values (90, 2);
insert into student_subject (student_id, subject_id) values (64, 6);
insert into student_subject (student_id, subject_id) values (11, 2);
insert into student_subject (student_id, subject_id) values (91, 6);
insert into student_subject (student_id, subject_id) values (66, 2);
insert into student_subject (student_id, subject_id) values (18, 4);
insert into student_subject (student_id, subject_id) values (8, 2);
insert into student_subject (student_id, subject_id) values (34, 1);
insert into student_subject (student_id, subject_id) values (15, 1);
insert into student_subject (student_id, subject_id) values (55, 3);
insert into student_subject (student_id, subject_id) values (55, 6);
insert into student_subject (student_id, subject_id) values (22, 1);
insert into student_subject (student_id, subject_id) values (43, 1);
insert into student_subject (student_id, subject_id) values (17, 6);
insert into student_subject (student_id, subject_id) values (41, 5);
insert into student_subject (student_id, subject_id) values (100, 3);
insert into student_subject (student_id, subject_id) values (45, 6);
insert into student_subject (student_id, subject_id) values (72, 5);
insert into student_subject (student_id, subject_id) values (98, 1);
insert into student_subject (student_id, subject_id) values (54, 4);
insert into student_subject (student_id, subject_id) values (27, 2);
insert into student_subject (student_id, subject_id) values (30, 3);
insert into student_subject (student_id, subject_id) values (72, 3);
insert into student_subject (student_id, subject_id) values (45, 4);
insert into student_subject (student_id, subject_id) values (87, 1);
insert into student_subject (student_id, subject_id) values (97, 5);
insert into student_subject (student_id, subject_id) values (29, 4);
insert into student_subject (student_id, subject_id) values (57, 3);
insert into student_subject (student_id, subject_id) values (56, 2);
insert into student_subject (student_id, subject_id) values (18, 2);
insert into student_subject (student_id, subject_id) values (16, 6);
insert into student_subject (student_id, subject_id) values (33, 4);
insert into student_subject (student_id, subject_id) values (52, 6);
insert into student_subject (student_id, subject_id) values (41, 1);
insert into student_subject (student_id, subject_id) values (3, 1);
insert into student_subject (student_id, subject_id) values (32, 1);
insert into student_subject (student_id, subject_id) values (64, 5);
insert into student_subject (student_id, subject_id) values (49, 2);
insert into student_subject (student_id, subject_id) values (61, 5);
insert into student_subject (student_id, subject_id) values (6, 4);
insert into student_subject (student_id, subject_id) values (18, 6);
insert into student_subject (student_id, subject_id) values (28, 5);
insert into student_subject (student_id, subject_id) values (69, 6);
insert into student_subject (student_id, subject_id) values (71, 2);
insert into student_subject (student_id, subject_id) values (95, 1);
insert into student_subject (student_id, subject_id) values (69, 3);
insert into student_subject (student_id, subject_id) values (47, 6);
insert into student_subject (student_id, subject_id) values (68, 2);
insert into student_subject (student_id, subject_id) values (64, 4);
insert into student_subject (student_id, subject_id) values (100, 5);
insert into student_subject (student_id, subject_id) values (39, 3);
insert into student_subject (student_id, subject_id) values (82, 4);
insert into student_subject (student_id, subject_id) values (88, 5);
insert into student_subject (student_id, subject_id) values (48, 2);
insert into student_subject (student_id, subject_id) values (28, 3);
insert into student_subject (student_id, subject_id) values (95, 2);
insert into student_subject (student_id, subject_id) values (14, 4);
insert into student_subject (student_id, subject_id) values (35, 2);
insert into student_subject (student_id, subject_id) values (79, 2);
insert into student_subject (student_id, subject_id) values (64, 2);
insert into student_subject (student_id, subject_id) values (17, 3);
insert into student_subject (student_id, subject_id) values (34, 3);
insert into student_subject (student_id, subject_id) values (85, 4);
insert into student_subject (student_id, subject_id) values (90, 4);
insert into student_subject (student_id, subject_id) values (83, 1);
insert into student_subject (student_id, subject_id) values (1, 4);
insert into student_subject (student_id, subject_id) values (57, 2);
insert into student_subject (student_id, subject_id) values (69, 1);
insert into student_subject (student_id, subject_id) values (28, 2);
insert into student_subject (student_id, subject_id) values (11, 1);
insert into student_subject (student_id, subject_id) values (33, 6);
insert into student_subject (student_id, subject_id) values (35, 6);
insert into student_subject (student_id, subject_id) values (75, 3);
insert into student_subject (student_id, subject_id) values (93, 6);
insert into student_subject (student_id, subject_id) values (6, 2);
insert into student_subject (student_id, subject_id) values (17, 4);
insert into student_subject (student_id, subject_id) values (20, 4);
insert into student_subject (student_id, subject_id) values (68, 3);
insert into student_subject (student_id, subject_id) values (26, 3);
insert into student_subject (student_id, subject_id) values (98, 3);
insert into student_subject (student_id, subject_id) values (8, 3);
insert into student_subject (student_id, subject_id) values (57, 6);
insert into student_subject (student_id, subject_id) values (86, 3);